name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main,deploy ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Instalar Git LFS
        run: git lfs install

      - name: Configurar identidade do Git
        run: |
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"

      - name: Push para o Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://Lucas-255:$HF_TOKEN@huggingface.co/spaces/Lucas-255/pisi3-dash
          git push --force hf HEAD:main